resilience4j:
  circuitbreaker:
    configs:
      defecto:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
    instances:
      productos:
        baseConfig: defecto
  timelimiter:
    configs:
      defecto:
        timeoutDuration: 2s
    instances:
      productos:
        baseConfig: defecto

spring:
  cloud:
    gateway:
      routes:
        - id: servicio-productos
          uri: lb://servicio-productos
          predicates:
            - Path=/api-productos/**
          filters:
            - name: CircuitBreaker
              args:
                name: productos
                statusCodes: 500
                fallbackUri: forward:/api-items/items/producto/2/cantidad/5
            - StripPrefix=1
            - FilterCookie=Hola esto es una prueba 2, usuario, GHernandez
        - id: servicio-items
          uri: lb://servicio-items
          predicates:
            - Path=/api-items/**
          filters:
            - StripPrefix=1
        - id: servicio-usuarios
          uri: lb://servicio-usuarios
          predicates:
            - Path=/api-usuarios/**
          filters:
            - StripPrefix=1



#version con los argumentos
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: servicio-productos
#          uri: lb://servicio-productos
#          predicates:
#            - Path=/api-productos/**
#          filters:
#            - StripPrefix=1
#            - name: Ejemplo
#              args:
#                mensaje: Hola esto es una prueba
#                cookieNombre: usuario
#                cookieValor: GiovanniHernandez
#        - id: servicio-items
#          uri: lb://servicio-items
#          predicates:
#            - Path=/api-items/**
#          filters:
#            - StripPrefix=1